spring.application.name=gc-latency-benchmark

spring.datasource.url=jdbc:postgresql://localhost:5432/payments
spring.datasource.username=payments
spring.datasource.password=payments
spring.datasource.hikari.maximum-pool-size=50

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.threads.virtual.enabled=true

server.tomcat.threads.max=200
